---

quotes_repo: git@github.com:davidmcclure/quotes.git
quotes_branch: master

quotes_dirs:
  code: /share/PI/malgeehe/code/quotes
  config: /share/PI/malgeehe/config/quotes
  sbatch: /share/PI/malgeehe/sbatch/quotes
  data: /scratch/PI/malgeehe/data/quotes

quotes_data_dirs:
  results: '{{ quotes_dirs.data }}/results'
  texts: '{{ quotes_dirs.data }}/texts'

# ****

quotes_config:

  database: '{{ quotes_dirs.data }}/quotes.db'

  stacks_dirs:
    - /scratch/PI/malgeehe/data/stacks/ext/chicago
    - /scratch/PI/malgeehe/data/stacks/ext/gail-amfic

  text_paths:
    kjb: '{{ quotes_data_dirs.texts }}/kjb.txt'
    hamlet: '{{ quotes_data_dirs.texts }}/hamlet.txt'

  result_dir: '{{ quotes_data_dirs.results }}'

# ****

quotes_sbatch_mpi:

  - name: query-kjb
    time: 03:00:00
    nodes: 2
    tasks: 16
    mem: 64000

  - name: query-hamlet
    time: 01:00:00
    nodes: 1
    tasks: 16
    mem: 64000

quotes_sbatch:

  - name: gather
    time: 01:00:00
    nodes: 1
    tasks: 1
    mem: 4000
