---

quotes_repo: git@github.com:davidmcclure/quotes.git
quotes_branch: feature/c19

quotes_dirs:
  code: /share/PI/malgeehe/code/quotes
  config: /share/PI/malgeehe/config/quotes
  sbatch: /share/PI/malgeehe/sbatch/quotes
  data: /scratch/PI/malgeehe/data/quotes

quotes_data_dirs:
  results: '{{ quotes_dirs.data }}/results'
  texts: '{{ quotes_dirs.data }}/texts'

stacks_data: /scratch/PI/malgeehe/data/stacks

# ****

quotes_config:

  database: '{{ quotes_dirs.data }}/quotes.db'

  chadh_corpus_dir: '{{ quotes_dirs.data }}/texts/chadh'

  stacks_db_url: 'sqlite:///{{ stacks_data }}/metadata.db'

  result_dir: '{{ quotes_data_dirs.results }}'

# ****

quotes_sbatch_mpi:

  # test
  - name: query-waverly
    time: 00:10:00
    nodes: 1
    tasks: 1
    mem: 4000

quotes_sbatch:

  - name: gather
    time: 01:00:00
    nodes: 1
    tasks: 1
    mem: 4000
